domain: 2
codomain: [3]
hidden_size: [256,256,256,256,256]
batch_size: 5
activ_func: sine
final_non_linearity: sigmoid
omega0: 1.0 # x ~= 11.0 (between 10 and 12)
omega0_initial: 0.04 # 0.04 >= x >= 0.03